query PostIndexPage {
  articles: posts(type: ["article"]) {
    id
    title
    type
    publishDate
    emoji
  }
  diaries: posts(type: ["diary"]) {
    id
    title
    type
    publishDate
    emoji
  }
}
